# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wxwh/share/gr_gpu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wxwh/share/gr_gpu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wxwh/share/gr_gpu/CMakeFiles /home/wxwh/share/gr_gpu//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wxwh/share/gr_gpu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named route

# Build rule for target.
route: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 route
.PHONY : route

# fast build rule for target.
route/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/build
.PHONY : route/fast

#=============================================================================
# Target rules for targets named flute

# Build rule for target.
flute: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flute
.PHONY : flute

# fast build rule for target.
flute/fast:
	$(MAKE) $(MAKESILENT) -f flute/CMakeFiles/flute.dir/build.make flute/CMakeFiles/flute.dir/build
.PHONY : flute/fast

src/gr/GRNet.o: src/gr/GRNet.cpp.o
.PHONY : src/gr/GRNet.o

# target to build an object file
src/gr/GRNet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/gr/GRNet.cpp.o
.PHONY : src/gr/GRNet.cpp.o

src/gr/GRNet.i: src/gr/GRNet.cpp.i
.PHONY : src/gr/GRNet.i

# target to preprocess a source file
src/gr/GRNet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/gr/GRNet.cpp.i
.PHONY : src/gr/GRNet.cpp.i

src/gr/GRNet.s: src/gr/GRNet.cpp.s
.PHONY : src/gr/GRNet.s

# target to generate assembly for a file
src/gr/GRNet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/gr/GRNet.cpp.s
.PHONY : src/gr/GRNet.cpp.s

src/gr/GRTree.o: src/gr/GRTree.cpp.o
.PHONY : src/gr/GRTree.o

# target to build an object file
src/gr/GRTree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/gr/GRTree.cpp.o
.PHONY : src/gr/GRTree.cpp.o

src/gr/GRTree.i: src/gr/GRTree.cpp.i
.PHONY : src/gr/GRTree.i

# target to preprocess a source file
src/gr/GRTree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/gr/GRTree.cpp.i
.PHONY : src/gr/GRTree.cpp.i

src/gr/GRTree.s: src/gr/GRTree.cpp.s
.PHONY : src/gr/GRTree.s

# target to generate assembly for a file
src/gr/GRTree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/gr/GRTree.cpp.s
.PHONY : src/gr/GRTree.cpp.s

src/gr/GlobalRouter.o: src/gr/GlobalRouter.cpp.o
.PHONY : src/gr/GlobalRouter.o

# target to build an object file
src/gr/GlobalRouter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/gr/GlobalRouter.cpp.o
.PHONY : src/gr/GlobalRouter.cpp.o

src/gr/GlobalRouter.i: src/gr/GlobalRouter.cpp.i
.PHONY : src/gr/GlobalRouter.i

# target to preprocess a source file
src/gr/GlobalRouter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/gr/GlobalRouter.cpp.i
.PHONY : src/gr/GlobalRouter.cpp.i

src/gr/GlobalRouter.s: src/gr/GlobalRouter.cpp.s
.PHONY : src/gr/GlobalRouter.s

# target to generate assembly for a file
src/gr/GlobalRouter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/gr/GlobalRouter.cpp.s
.PHONY : src/gr/GlobalRouter.cpp.s

src/gr/GridGraph.o: src/gr/GridGraph.cpp.o
.PHONY : src/gr/GridGraph.o

# target to build an object file
src/gr/GridGraph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/gr/GridGraph.cpp.o
.PHONY : src/gr/GridGraph.cpp.o

src/gr/GridGraph.i: src/gr/GridGraph.cpp.i
.PHONY : src/gr/GridGraph.i

# target to preprocess a source file
src/gr/GridGraph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/gr/GridGraph.cpp.i
.PHONY : src/gr/GridGraph.cpp.i

src/gr/GridGraph.s: src/gr/GridGraph.cpp.s
.PHONY : src/gr/GridGraph.s

# target to generate assembly for a file
src/gr/GridGraph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/gr/GridGraph.cpp.s
.PHONY : src/gr/GridGraph.cpp.s

src/gr/MazeRoute.o: src/gr/MazeRoute.cpp.o
.PHONY : src/gr/MazeRoute.o

# target to build an object file
src/gr/MazeRoute.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/gr/MazeRoute.cpp.o
.PHONY : src/gr/MazeRoute.cpp.o

src/gr/MazeRoute.i: src/gr/MazeRoute.cpp.i
.PHONY : src/gr/MazeRoute.i

# target to preprocess a source file
src/gr/MazeRoute.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/gr/MazeRoute.cpp.i
.PHONY : src/gr/MazeRoute.cpp.i

src/gr/MazeRoute.s: src/gr/MazeRoute.cpp.s
.PHONY : src/gr/MazeRoute.s

# target to generate assembly for a file
src/gr/MazeRoute.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/gr/MazeRoute.cpp.s
.PHONY : src/gr/MazeRoute.cpp.s

src/gr/PatternRoute.o: src/gr/PatternRoute.cpp.o
.PHONY : src/gr/PatternRoute.o

# target to build an object file
src/gr/PatternRoute.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/gr/PatternRoute.cpp.o
.PHONY : src/gr/PatternRoute.cpp.o

src/gr/PatternRoute.i: src/gr/PatternRoute.cpp.i
.PHONY : src/gr/PatternRoute.i

# target to preprocess a source file
src/gr/PatternRoute.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/gr/PatternRoute.cpp.i
.PHONY : src/gr/PatternRoute.cpp.i

src/gr/PatternRoute.s: src/gr/PatternRoute.cpp.s
.PHONY : src/gr/PatternRoute.s

# target to generate assembly for a file
src/gr/PatternRoute.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/gr/PatternRoute.cpp.s
.PHONY : src/gr/PatternRoute.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/multithread/Scheduler.o: src/multithread/Scheduler.cpp.o
.PHONY : src/multithread/Scheduler.o

# target to build an object file
src/multithread/Scheduler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/multithread/Scheduler.cpp.o
.PHONY : src/multithread/Scheduler.cpp.o

src/multithread/Scheduler.i: src/multithread/Scheduler.cpp.i
.PHONY : src/multithread/Scheduler.i

# target to preprocess a source file
src/multithread/Scheduler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/multithread/Scheduler.cpp.i
.PHONY : src/multithread/Scheduler.cpp.i

src/multithread/Scheduler.s: src/multithread/Scheduler.cpp.s
.PHONY : src/multithread/Scheduler.s

# target to generate assembly for a file
src/multithread/Scheduler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/multithread/Scheduler.cpp.s
.PHONY : src/multithread/Scheduler.cpp.s

src/obj/GeoTypes.o: src/obj/GeoTypes.cpp.o
.PHONY : src/obj/GeoTypes.o

# target to build an object file
src/obj/GeoTypes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/obj/GeoTypes.cpp.o
.PHONY : src/obj/GeoTypes.cpp.o

src/obj/GeoTypes.i: src/obj/GeoTypes.cpp.i
.PHONY : src/obj/GeoTypes.i

# target to preprocess a source file
src/obj/GeoTypes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/obj/GeoTypes.cpp.i
.PHONY : src/obj/GeoTypes.cpp.i

src/obj/GeoTypes.s: src/obj/GeoTypes.cpp.s
.PHONY : src/obj/GeoTypes.s

# target to generate assembly for a file
src/obj/GeoTypes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/obj/GeoTypes.cpp.s
.PHONY : src/obj/GeoTypes.cpp.s

src/obj/ISPD24Parser.o: src/obj/ISPD24Parser.cpp.o
.PHONY : src/obj/ISPD24Parser.o

# target to build an object file
src/obj/ISPD24Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/obj/ISPD24Parser.cpp.o
.PHONY : src/obj/ISPD24Parser.cpp.o

src/obj/ISPD24Parser.i: src/obj/ISPD24Parser.cpp.i
.PHONY : src/obj/ISPD24Parser.i

# target to preprocess a source file
src/obj/ISPD24Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/obj/ISPD24Parser.cpp.i
.PHONY : src/obj/ISPD24Parser.cpp.i

src/obj/ISPD24Parser.s: src/obj/ISPD24Parser.cpp.s
.PHONY : src/obj/ISPD24Parser.s

# target to generate assembly for a file
src/obj/ISPD24Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/obj/ISPD24Parser.cpp.s
.PHONY : src/obj/ISPD24Parser.cpp.s

src/utils/log.o: src/utils/log.cpp.o
.PHONY : src/utils/log.o

# target to build an object file
src/utils/log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/utils/log.cpp.o
.PHONY : src/utils/log.cpp.o

src/utils/log.i: src/utils/log.cpp.i
.PHONY : src/utils/log.i

# target to preprocess a source file
src/utils/log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/utils/log.cpp.i
.PHONY : src/utils/log.cpp.i

src/utils/log.s: src/utils/log.cpp.s
.PHONY : src/utils/log.s

# target to generate assembly for a file
src/utils/log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/utils/log.cpp.s
.PHONY : src/utils/log.cpp.s

src/utils/parameters.o: src/utils/parameters.cpp.o
.PHONY : src/utils/parameters.o

# target to build an object file
src/utils/parameters.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/utils/parameters.cpp.o
.PHONY : src/utils/parameters.cpp.o

src/utils/parameters.i: src/utils/parameters.cpp.i
.PHONY : src/utils/parameters.i

# target to preprocess a source file
src/utils/parameters.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/utils/parameters.cpp.i
.PHONY : src/utils/parameters.cpp.i

src/utils/parameters.s: src/utils/parameters.cpp.s
.PHONY : src/utils/parameters.s

# target to generate assembly for a file
src/utils/parameters.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/route.dir/build.make CMakeFiles/route.dir/src/utils/parameters.cpp.s
.PHONY : src/utils/parameters.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... flute"
	@echo "... route"
	@echo "... src/gr/GRNet.o"
	@echo "... src/gr/GRNet.i"
	@echo "... src/gr/GRNet.s"
	@echo "... src/gr/GRTree.o"
	@echo "... src/gr/GRTree.i"
	@echo "... src/gr/GRTree.s"
	@echo "... src/gr/GlobalRouter.o"
	@echo "... src/gr/GlobalRouter.i"
	@echo "... src/gr/GlobalRouter.s"
	@echo "... src/gr/GridGraph.o"
	@echo "... src/gr/GridGraph.i"
	@echo "... src/gr/GridGraph.s"
	@echo "... src/gr/MazeRoute.o"
	@echo "... src/gr/MazeRoute.i"
	@echo "... src/gr/MazeRoute.s"
	@echo "... src/gr/PatternRoute.o"
	@echo "... src/gr/PatternRoute.i"
	@echo "... src/gr/PatternRoute.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/multithread/Scheduler.o"
	@echo "... src/multithread/Scheduler.i"
	@echo "... src/multithread/Scheduler.s"
	@echo "... src/obj/GeoTypes.o"
	@echo "... src/obj/GeoTypes.i"
	@echo "... src/obj/GeoTypes.s"
	@echo "... src/obj/ISPD24Parser.o"
	@echo "... src/obj/ISPD24Parser.i"
	@echo "... src/obj/ISPD24Parser.s"
	@echo "... src/utils/log.o"
	@echo "... src/utils/log.i"
	@echo "... src/utils/log.s"
	@echo "... src/utils/parameters.o"
	@echo "... src/utils/parameters.i"
	@echo "... src/utils/parameters.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

